### ISSUE TITLE
Ore dictionary management

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconArchive#1]
Various ores and (probably) their processed forms are added by different mods in this pack. Example: Copper is added by both Thermal Foundation and ProjectRed Expansion.

An ore dictionary pass should be performed to reduce the number of duplicate item types, specifically ores, dusts, and ingots.

**Comment by Almagnus1** [comment]
That's a good checkmark for Beta - noting it at https://github.com/Almagnus1/IaconClient/issues/2 and closing this issue.
